KEYSTONE_URL="http://localhost:5000/v2.0/tokens"
KEYSTONE_URL_V3="http://localhost:5000/v3/auth/tokens"
KEYSTONE_USER="tempest_u1"
KEYSTONE_ACCT="tempest"
KEYSTONE_PASS="tempest"

TEMPAUTH_URL="http://localhost:8002/auth/v1.0/"
#TEMPAUTH_URL="http://localhost:8000/auth/v1.0/"
TEMPAUTH_USER="tester"
TEMPAUTH_PASS="testing"
TEMPAUTH_ACCT="test"
